import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-sales-use-tax-reverse-audit-refund",
  "engine": "recovery",
  "title": "Sales & Use Tax Reverse-Audit Refund",
  "shortTitle": "Sales and Use Tax Reverse-Audit Refund",
  "tagline": "Find overpaid sales and use tax and prepare defensible vendor-credit or jurisdiction-refund claims.",
  "industry": "Indirect Tax Recovery",
  "buyer": "Multi-state businesses and tax departments",
  "uiPort": 4683,
  "apiPort": 5683,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Sales & Use Tax Reverse-Audit Refund converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds in one accountable workflow. Find overpaid sales and use tax and prepare defensible vendor-credit or jurisdiction-refund claims.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Sales & Use Tax Reverse-Audit Refund evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("transaction-ingestion","SUT01","Transaction ingestion","Execute transaction ingestion using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Transaction ingestion Reference","text","SUT01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("tax-code-normalization","SUT02","Tax code normalization","Execute tax code normalization using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed tax code normalization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Tax code normalization Reference","text","SUT02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("product-service-classification","SUT03","Product service classification","Execute product service classification using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed product service classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Product service classification Reference","text","SUT03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("use-location-determination","SUT04","Use location determination","Execute use location determination using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed use location determination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Use location determination Reference","text","SUT04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("jurisdiction-rate-validation","SUT05","Jurisdiction rate validation","Execute jurisdiction rate validation using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed jurisdiction rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Jurisdiction rate validation Reference","text","SUT05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("exemption-mapping","SUT06","Exemption mapping","Execute exemption mapping using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed exemption mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Exemption mapping Reference","text","SUT06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("manufacturing-exemption","SUT07","Manufacturing exemption","Execute manufacturing exemption using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed manufacturing exemption decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Manufacturing exemption Reference","text","SUT07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("resale-exemption","SUT08","Resale exemption","Execute resale exemption using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed resale exemption decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Resale exemption Reference","text","SUT08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("duplicate-accrual-detection","SUT09","Duplicate accrual detection","Execute duplicate accrual detection using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed duplicate accrual detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Duplicate accrual detection Reference","text","SUT09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("vendor-tax-error-detection","SUT10","Vendor tax error detection","Execute vendor tax error detection using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed vendor tax error detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Vendor tax error detection Reference","text","SUT10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("refund-statute-monitoring","SUT11","Refund statute monitoring","Execute refund statute monitoring using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed refund statute monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Refund statute monitoring Reference","text","SUT11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("sample-projection-control","SUT12","Sample projection control","Execute sample projection control using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed sample projection control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Sample projection control Reference","text","SUT12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("claim-evidence-package","SUT13","Claim evidence package","Execute claim evidence package using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed claim evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Claim evidence package Reference","text","SUT13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("refund-cash-tracking","SUT14","Refund cash tracking","Execute refund cash tracking using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed refund cash tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Refund cash tracking Reference","text","SUT14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]}),
feature("entity-jurisdiction-analytics","SUT15","Entity jurisdiction analytics","Execute entity jurisdiction analytics using purchase transactions, invoices, tax codes, product use, exemptions, jurisdiction rates, accruals, vendor credits, refund statutes, claims, and refunds.","Produce a governed entity jurisdiction analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Transaction Population","text","Entity / Transaction Population · Standard Case"],["caseReference","Entity jurisdiction analytics Reference","text","SUT15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1057500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1279575],["domainDriver","Refund Basis","select","Exempt purchase",["Exempt purchase","Wrong jurisdiction","Duplicate accrual"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Transaction ingestion case","Tax code normalization case","Product service classification case","Use location determination case","Jurisdiction rate validation case"]})
]);
